from selenium import webdriver
import time
driver=webdriver.Chrome()
driver.get('https://www.baidu.com/')
driver.maximize_window()
driver.find_element_by_id('kw').send_keys('qq邮箱')
driver.find_element_by_id('su').click()
time.sleep(3)
driver.find_element_by_xpath('//*[@id="1"]/h3/a[1]').click()
time.sleep(5)
driver.switch_to.window(driver.window_handles[-1])
driver.switch_to.frame(driver.find_element_by_xpath('//*[@id="login_frame"]'))
time.sleep(3)
driver.find_element_by_id('switcher_plogin').click()
time.sleep(3)
driver.find_element_by_xpath('//*[@id="u"]').send_keys('452990633')
driver.find_element_by_xpath('//*[@id="p"]').send_keys('452990633cxm')
driver.find_element_by_xpath('//*[@id="login_button"]').click()
time.sleep(3)
driver.switch_to.window(driver.window_handles[-1])
driver.find_element_by_xpath('//*[@id="composebtn"]').click()
time.sleep(3)
driver.switch_to.frame(driver.find_element_by_xpath('//*[@id="mainFrame"]'))
driver.find_element_by_xpath('//*[@id="toAreaCtrl"]/div[2]/input').send_keys('1048596163@qq.com;')
time.sleep(3)
driver.find_element_by_name('UploadFile').send_keys('C:\\1.txt')
time.sleep(5)
driver.find_element_by_css_selector('#toolbar > div.toolbg.toolbgline > a:nth-child(2)').click()
driver.close()
